name: odapi_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - geopandas
  - pyarrow
  - plotly
  - streamlit
  - pip:
    - python-dotenv
    - statsmodels
